---
spec/spec_helper.rb:
  mock_with: ':rspec'
spec/default_facts.yml:
  extra_facts:
    path: "/bin:/usr/bin:/usr/local/bin"
.gitlab-ci.yml:
  custom:
    custom_stages:
      - smoke
    custom_jobs:
      smoke syslog-ng puppet 5:
        stage: smoke
        image: ruby:2.5.3
        variables:
          PUPPET_GEM_VERSION: '~> 5'
        script:
          - apt-get update
          - apt-get install syslog-ng -y
          - syslog-ng --version
          - bundle install --without system_tests --path vendor/bundle
          - bundle exec puppet --version
          - bundle exec puppet module build
          - bundle exec puppet module install pkg/*.tar.gz
          - bundle exec ./smoke/test
      smoke syslog-ng latest:
        stage: smoke
        allow_failure: true
        image:
          name: balabit/syslog-ng:latest
          entrypoint: [""]
        before_script: []
        script:
          - 'apt update || :'
          - apt install ruby bundler -y
          - bundle install --without system_tests --path vendor/bundle
          - bundle exec puppet --version
          - bundle exec puppet module build
          - bundle exec puppet module install pkg/*.tar.gz
          - bundle exec ./smoke/test
.travis.yml:
  stages:
    - smoke
  extras:
    -
      env: PUPPET_GEM_VERSION="~> 5.0" CHECK=parallel_spec USE_PDK=1
      rvm: 2.4.5
      stage: smoke
      script:
        - 'bundle exec puppet --version'
        - 'bundle exec puppet module build'
        - 'bundle exec puppet module install pkg/*.tar.gz'
        - 'bundle exec ./smoke/test -d'
  addons:
    apt:
      packages:
        - syslog-ng-core
