language: ruby

#bundler_args: --without development

addons:
  apt:
    packages:
      - syslog-ng
      - puppet

install:
  - bundle install

before_script:
  - mkdir -p ~/.puppet/modules
  - ln -s $PWD ~/.puppet/modules/patterndb
  - git clone https://github.com/puppetlabs/puppetlabs-stdlib ~/.puppet/modules/stdlib
  - git clone https://github.com/puppetlabs/puppetlabs-concat ~/.puppet/modules/concat

script:
  - bundle exec rake SPEC_OPTS='--format documentation'
  - ./smoke/test

rvm:
  - 2.1.9
  - 2.3.4
  - 2.4.1

env:
  matrix:
    - PUPPET_GEM_VERSION="~> 3.0" FIXTURES_YML=.fixtures-old.yml
    - PUPPET_GEM_VERSION="~> 3.1" FIXTURES_YML=.fixtures-old.yml
    - PUPPET_GEM_VERSION="~> 3.2" FIXTURES_YML=.fixtures-old.yml
    - PUPPET_GEM_VERSION="~> 3.3" FIXTURES_YML=.fixtures-old.yml
    - PUPPET_GEM_VERSION="~> 3.4" FIXTURES_YML=.fixtures-old.yml
    - PUPPET_GEM_VERSION="~> 3.5" FIXTURES_YML=.fixtures-old.yml
    - PUPPET_GEM_VERSION="~> 4.0.0" FIXTURES_YML=.fixtures.yml
    - PUPPET_GEM_VERSION="~> 4.5.0" FIXTURES_YML=.fixtures.yml
    - PUPPET_GEM_VERSION="~> 4.9.1" FIXTURES_YML=.fixtures.yml
    - PUPPET_GEM_VERSION="~> 4.10.10" FIXTURES_YML=.fixtures.yml
    - PUPPET_GEM_VERSION="~> 5.4.0" FIXTURES_YML=.fixtures.yml
matrix:
  fast_finish: true
#  exclude:
#    - rvm: 1.8.7
#      env: PUPPET_GEM_VERSION="~> 3.2.0"

notifications:
    email:
      recipients:
        - wernli@in2p3.fr
      on_success: change
      on_failure: always
