language: ruby

addons:
  apt:
    packages:
      - syslog-ng-core

install:
  - bundle install

before_script:
  - bundle install
  - bundle exec puppet --version
  - bundle exec puppet module build
  - bundle exec puppet module install pkg/*.tar.gz

script:
  - bundle exec rake spec
  - bundle exec ./smoke/test

rvm:
  - 2.1.9
  - 2.3.4
  - 2.4.1

env:
  matrix:
    - PUPPET_GEM_VERSION="~> 4.9.1" FIXTURES_YML=.fixtures-old.yml
    - PUPPET_GEM_VERSION="~> 4.10.10" FIXTURES_YML=.fixtures-old.yml
    - PUPPET_GEM_VERSION="~> 5.0.0" FIXTURES_YML=.fixtures-old.yml
    - PUPPET_GEM_VERSION="~> 5.4.0" FIXTURES_YML=.fixtures-old.yml
    - PUPPET_GEM_VERSION="~> 5.5.0" FIXTURES_YML=.fixtures-old.yml
    - PUPPET_GEM_VERSION="~> 4.9.1" FIXTURES_YML=.fixtures.yml
    - PUPPET_GEM_VERSION="~> 4.10.10" FIXTURES_YML=.fixtures.yml
    - PUPPET_GEM_VERSION="~> 5.0.0" FIXTURES_YML=.fixtures.yml
    - PUPPET_GEM_VERSION="~> 5.4.0" FIXTURES_YML=.fixtures.yml
    - PUPPET_GEM_VERSION="~> 5.5.0" FIXTURES_YML=.fixtures.yml
matrix:
  fast_finish: true
#  exclude:
#    - rvm: 1.8.7
#      env: PUPPET_GEM_VERSION="~> 3.2.0"

notifications:
    email:
      recipients:
        - wernli@in2p3.fr
      on_success: change
      on_failure: always
